version: '3.3'
services:
  app:
    build: .
    ports:
      - 4500:8080
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: bd_examen
    
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
   
    ports:
      -  9898:27017
    

volumes:
  mongo-data: